version: '3.3'

services:
  production:
    build: 
      context: .
      dockerfile: ./docker/production/Dockerfile
    container_name:  nft-toolkit-production
    ports:
      - '3036:3035'
    environment:
      - NODE_ENV=production

  staging:
    build: 
      context: .
      dockerfile: ./docker/staging/Dockerfile
    container_name:  nft-tookit-staging
    ports:
      - '8095:3035'
    environment:
      - NODE_ENV=staging

  beta:
    build: 
      context: .
      dockerfile: ./docker/staging/Dockerfile
    container_name:  nft-tookit-staging-beta
    ports:
      - '8096:3035'
    environment:
      - NODE_ENV=staging


      